before_script:
  - bundle exec rake test_app
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  bundler: true

install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

env:
  - DB=mysql
  - DB=postgres
language: ruby
rvm:
  - 2.3.1
  - 2.2.5

sudo: false
